version: '3.8'

services:
  app:
    image: hjiria/tpfoyer-17:0.0.1
    container_name: tpfoyer-app
    ports:
      - "8089:8082"  # Mappe le port 8089 du conteneur au port 8089 de l'hôte
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb  # URL de la base de données
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db  # Assurez-vous que le conteneur db est démarré avant
    volumes:
      - app_data:/app/data

  db:
    image: mysql:8
    container_name: tpfoyer-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb  # Base de données par défaut
      MYSQL_USER: root  # Ajout de l'utilisateur
      MYSQL_PASSWORD: root  # Ajout du mot de passe pour l'utilisateur
    ports:
      - "3306:3306"  # Expose le port MySQL
    volumes:
      - db_data:/var/lib/mysql  # Persistance des données

volumes:
  db_data:
    driver: local
  app_data: {}
