version: '3.8'

services:
  mmysql:
    image: mysql
    container_name: tpfoyer-db
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpFoyer17
      MYSQL_USER: amir
      MYSQL_PASSWORD: amir1234

    ports:
      - "3308:3306"
    networks:
      - spring_mysql

  spring-boot-app:
    container_name: tpfoyer-app
    build: ./tpFoyer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mmysql
    environment:
      MYSQL_HOST: mmysql
      MYSQL_USER: amir
      MYSQL_PASSWORD: amir1234
      MYSQL_PORT: 3306
    networks:
      - spring_mysql
networks:
  spring_mysql:
    driver: bridge