version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: roote  # Le mot de passe root pour la base de données
      MYSQL_DATABASE: tpFoyer17  # Le nom de la base de données
    ports:
      - "3306:3306"  # Expose le port MySQL
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  backend:
    image: hjiriamir/tpfoyer-17:0.0.1
    container_name: backend
    restart: on-failure
    ports:
      - 8082:8082  # Utiliser le port défini dans application.properties
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://db:3306/tpFoyer17?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username": "root",
        "spring.datasource.password": "roote",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true
    depends_on:
      - db  # S'assure que db est démarré avant le backend
    networks:
      - mynetwork

volumes:
  mysql_data:  # Nom du volume pour persister les données MySQL
    driver: local

networks:
  mynetwork:
    driver: bridge
