version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: tpfoyer-db
    restart: unless-stopped

    ports:
        - "3306:3306"  # Expose le port MySQL
    volumes:
          - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root  # Base de données par défaut

    networks:
      - mynetwork
    # Persistance des données
  springboot:
    image: hjiria/tpfoer-17:latest
    container_name: tpfoyer-app
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
        - mynetwork
volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
